openapi: 3.0.0
components:
  schemas: {}
  securitySchemes: {}
info:
  title: Serverless Node
  description: Serverless Node
  version: 1.0.0
paths:
  /api/swapi:
    get:
      summary: Star Wars API
      description: Integración de Star Wars API
      responses:
        "200":
          description: Star Wars API integrada correctamente

        "400":
          description: Error al integrar Star Wars API

  /api/school/listarAlumnos:
    get:
      summary: Listar Alumnos
      description: Listar todos los alumnos registrados
      responses:
        "200":
          description: Alumnos listados correctamente

        "400":
          description: Error al listar alumnos

  /api/school/crearAlumno:
    post:
      summary: Crear Alumno
      description: Crear un alumno nuevo
      responses:
        "200":
          description: Alumno creado correctamente

        "400":
          description: Error al crear alumno
