service: serverless-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  personas:
    handler: src/personas/controller.handler
    events:
      - http:
          path: personas/listar
          method: get
      - http:
          path: personas/listar/{idpersona}
          method: get
      - http:
          path: personas/agregar
          method: post
      - http:
          path: personas/editar
          method: put
      - http:
          path: personas/eliminar/{idpersona}
          method: delete
  cuentas:
    handler: src/cuentas/controller.handler
    events:
      - http:
          path: cuentas/listar/{idpersona}
          method: get
      - http:
          path: cuentas/agregar
          method: post
      - http:
          path: cuentas/editar
          method: put
      - http:
          path: cuentas/eliminar/{idcuenta}
          method: delete
  transacciones:
    handler: src/transacciones/controller.handler
    events:
      - http:
          path: transacciones/listar/{idcuenta}
          method: get
      - http:
          path: transacciones/agregar
          method: post
      - http:
          path: transacciones/editar
          method: put
      - http:
          path: transacciones/eliminar/{idtransaccion}
          method: delete

plugins:
  - serverless-offline
