service: serverless-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  listar:
    handler: src/gfs/listar/controller.listar
    events:
      - http:
          path: /listar
          method: get

plugins:
  - serverless-offline
