service: serverless-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  gfs:
    handler: src/gfs/controller.handler
    events:
      - http:
          path: /listar
          method: get
      - http:
          path: /listar/{idgf}
          method: get
      - http:
          path: /agregar
          method: post
      - http:
          path: /editar
          method: put
      - http:
          path: /eliminar/{idgf}
          method: delete

plugins:
  - serverless-offline
